name: "Pistas Workflow"

on:
  push:
    branches:
    - main

jobs:
  build-clients:
    name: Build clients
    runs-on: ubuntu-latest
    strategy:
      # Don't cancel other OS runners if one fails.
      fail-fast: false
      matrix:
        target: [windows, linux]
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      
      - uses: chickensoft-games/setup-godot@v1
        name: Setup Godot
        with:
          version: 4.3.0-beta.2 
          use-dotnet: false
          include-templates: true

      - name: Prepare dist 
        run: mkdir -p dist/${{ matrix.target }}

      - name: Verify Setup
        run: godot --version

      - name: Export release
        run: godot --headless --export-release ${{ matrix.target }}

      - uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: ${{ matrix.target }}
          ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
          PACKAGE: dist/${{ matrix.target }}
